import UserHeader from '@/components/UserHeader';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
  title: 'User Management',
  description: 'Generated by create next app',
};

export default function layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className='font-sans min-h-screen bg-gray-100 flex flex-col items-center justify-center  p-8'>
      <UserHeader />
      {/* 콘텐츠 */}
      <div className='w-full max-w-4xl'>{children}</div>
    </div>
  );
}
